version: '2' 

# docker network create -d bridge cassnet
networks:
  cassnet:
    external: true

services:
  cassandra1:
    #image: docker.io/bitnami/cassandra:4.0
    container_name: cassandra1
    image: bitnami/cassandra:3.11.10
    ports:
      - 7000:7000
      - 9042:9042
    networks:
      - cassnet
    volumes:
      - cassandra1_data:/bitnami
      #- ./data/cass1:/var/lib/cassandra    # This is the volume that will persist data for cass1 node
      #- ./etc/cass1:/etc/cassandra   # Use your own config files for full control
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra4,cassandra5 #,cassandra2    # The first two nodes will be seeds
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=aseno-cass
      - CASSANDRA_DATACENTER=rz1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch # SimpleSnitch #
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_HOST=cassandra1
      #- CASSANDRA_BROADCAST_ADDRESS=cassandra1
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=400M

  cassandra2:
    container_name: cassandra2
    image: bitnami/cassandra:3.11.10
    networks:
      - cassnet
    ports:
      - 7001:7000
      - 9043:9042
    volumes:
      - cassandra2_data:/bitnami
      #- ./data/cass2:/var/lib/cassandra    # This is the volume that will persist data for cass2 node
      #- ./etc/cass2:/etc/cassandra    # Use your own config files for full control
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra4,cassandra5 # The first two nodes will be seeds
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=aseno-cass
      - CASSANDRA_DATACENTER=rz1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      #- CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=400M
    #depends_on:
    #  - cassandra1
  cassandra3:
    container_name: cassandra3
    image: bitnami/cassandra:3.11.10
    networks:
      - cassnet
    ports:
      - 7002:7000
      - 9044:9042
    volumes:
      - cassandra3_data:/bitnami
      #- ./data/cass2:/var/lib/cassandra    # This is the volume that will persist data for cass2 node
      #- ./etc/cass2:/etc/cassandra    # Use your own config files for full control
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra4,cassandra5 # The first two nodes will be seeds
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=aseno-cass
      - CASSANDRA_DATACENTER=rz1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      #- CASSANDRA_BROADCAST_ADDRESS=cassandra3
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=400M

  cassandra4:
    container_name: cassandra4
    image: bitnami/cassandra:3.11.10
    networks:
      - cassnet
    ports:
      - 7003:7000
      - 9045:9042
    volumes:
      - cassandra4_data:/bitnami
      #- ./data/cass2:/var/lib/cassandra    # This is the volume that will persist data for cass2 node
      #- ./etc/cass2:/etc/cassandra    # Use your own config files for full control
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra4,cassandra5 #,cassandra4,cassandra5    # The first two nodes will be seeds
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=aseno-cass
      - CASSANDRA_DATACENTER=rz2
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      #- CASSANDRA_BROADCAST_ADDRESS=cassandra4
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=400M
  cassandra5:
    container_name: cassandra5
    image: bitnami/cassandra:3.11.10
    networks:
      - cassnet
    ports:
      - 7004:7000
      - 9046:9042
    volumes:
      - cassandra5_data:/bitnami
      #- ./data/cass2:/var/lib/cassandra    # This is the volume that will persist data for cass2 node
      #- ./etc/cass2:/etc/cassandra    # Use your own config files for full control
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra4,cassandra5 # The first two nodes will be seeds
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=aseno-cass
      - CASSANDRA_DATACENTER=rz2
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      #- CASSANDRA_BROADCAST_ADDRESS=cassandra5
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=400M

  cassandra6:
    container_name: cassandra6
    image: bitnami/cassandra:3.11.10
    networks:
      - cassnet
    ports:
      - 7005:7000
      - 9047:9042
    volumes:
      - cassandra6_data:/bitnami
      #- ./data/cass2:/var/lib/cassandra    # This is the volume that will persist data for cass2 node
      #- ./etc/cass2:/etc/cassandra    # Use your own config files for full control
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra4,cassandra5 # The first two nodes will be seeds
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_CLUSTER_NAME=aseno-cass
      - CASSANDRA_DATACENTER=rz2
      - CASSANDRA_RACK=rack2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_NUM_TOKENS=256
      #- CASSANDRA_BROADCAST_ADDRESS=cassandra6
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=400M

volumes:
  cassandra1_data:
    driver: local
  cassandra2_data:
    driver: local
  cassandra3_data:
    driver: local
  cassandra4_data:
    driver: local
  cassandra5_data:
    driver: local
  cassandra6_data:
    driver: local
