# This file is only use for a single node cassandra connection.
# To run the example, please use application-vfo.yaml file and spring profiles.
spring.application.name: spring-data-service

server.port: 8080

spring.data.cassandra:
  contact-points: localhost
  port: 9042
  local-datacenter: datacenter1
  keyspace-name: myks
  username: aseno
  password: password
  # Create the schema on the fly if it doesn't exist
  schema-action: CREATE_IF_NOT_EXISTS
  # Increase timeouts when connecting to Astra from a dev workstation
  request:
    timeout: 10s
  connection:
    connect-timeout: 10s
    init-query-timeout: 10s

driver.contactPoints: ${CASS_CONTACT_POINTS}
driver.localdc: ${CASS_LOCAL_DC}
driver.keyspace: ${CASS_KEYSPACE}
driver.consistency: ${CASS_CL}
driver.serialConsistency: ${CASS_SCL}
driver.retryPolicy: ${CASS_RETRY_POLICY}
driver.sessionName: val-sess
driver.pageSize: 8
driver.username: ${CASS_USER}
driver.password: ${CASS_PWD}