spring.application.name: spring-data-service

server.port: 8080

spring.data.cassandra:
  contact-points: ${CASS_CONTACT_POINTS}
  port: ${CASS_PORT}
  local-datacenter: ${CASS_LOCAL_DC}
  keyspace-name: ${CASS_KEYSPACE}
  username: ${CASS_USER}
  password: ${CASS_PWD}
  # Create the schema on the fly if it doesn't exist
  schema-action: CREATE_IF_NOT_EXISTS
  request:
    timeout: 10s
    # https://docs.datastax.com/en/archived/cassandra/3.0/cassandra/dml/dmlConfigConsistency.html
    consistency: ${CASS_CL}
    serial-consistency: ${CASS_SCL}
  connection:
    connect-timeout: 10s
    init-query-timeout: 10s

driver.contactPoints: ${CASS_CONTACT_POINTS}
driver.localdc: ${CASS_LOCAL_DC}
driver.keyspace: ${CASS_KEYSPACE}
driver.consistency: ${CASS_CL}
driver.serialConsistency: ${CASS_SCL}
driver.retryPolicy: ${CASS_RETRY_POLICY}
driver.sessionName: val-sess
driver.pageSize: 8
driver.username: ${CASS_USER}
driver.password: ${CASS_PWD}